

server:
  port: '8081'
spring:
  kafka:
    producer:
      acks: -1
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: kafka-log-topic
#    producer:
#      topic: kafka-log-topic
  application:
    name: user-service-main
  main:
    allow-bean-definition-overriding: 'true'
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}