
server:
  port: '8081'
spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL:localhost:9092}
    producer:
      topic: kafka-log-topic
  application:
    name: user-service-main
  main:
    allow-bean-definition-overriding: 'true'
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}