server:
  port: '5555'
spring:
  application:
    name: garanti-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: example
    url: jdbc:mysql://${MYSQL_DB_HOST:localhost}:3306/test?allowPublicKeyRetrieval=true&useSSL=false

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}