spring:
  application:
    name: logconsumer-service
  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      auto-offset-reset: earliest
      group-id: consumer-1
    topic:
        name: kafka-log-topic

  data:
    mongodb:
        host: ${MONGO_DB_HOST:localhost}
        port: 27017
        database: error-logs
        username: log-consumer
        password: example

server:
    port: 8084
