server:
  port: '8082'
spring:
  application:
    name: notification-service-main

  kafka:
    producer:
      acks: -1
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      error-topic: kafka-log-topic
      notification-topic: kafka-notification
    consumer:
      group-id: notification-service

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: kredinbizde1@gmail.com
    password: kredinbizde@14
    port: '587'
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}