server:
  port: '8083'

management:
  endpoint:
    health:
      show-details: always
  health:
    kafka:
      enabled: true
    redis:
      enabled: true
    defaults:
      enabled: false
spring:
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  application:
    name: bank-service-main
  kafka:
    producer:
      acks: -1
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    template:
      default-topic: kafka-log-topic
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}