server:
  port: '8080'
spring:
  application:
    name: application-service-main
#  rabbitmq:
#    host: ${SPRING_RABBITMQ_HOST:localhost}
#    port: ${SPRING_RABBITMQ_PORT:5672}
#    username: ${SPRING_RABBITMQ_USERNAME:admin}
#    password: ${SPRING_RABBITMQ_PASSWORD:123456}
#    listener:
#      simple:
#        default-requeue-rejected: false
#        concurrency: 3
#        max-concurrency: 10
#    template:
#      exchange: patika.exchange
#      routing-key: patika.routingkey
#      default-receive-queue: patika.queue

  kafka:
    producer:
      acks: -1
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    template:
      default-topic: kafka-log-topic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: example
    url: jdbc:mysql://${MYSQL_DB_HOST:localhost}:3306/test?allowPublicKeyRetrieval=true&useSSL=false

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  main:
    allow-bean-definition-overriding: 'true'
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
kafka:
    topic:
        name: kafka-log-topic
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}