server:
  port: '8080'
spring:
  application:
    name: application-service-main

  kafka:
    producer:
      acks: -1
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      error-topic: kafka-log-topic
      notification-topic: kafka-notification
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: example
    url: jdbc:mysql://${MYSQL_DB_HOST:localhost}:3306/test?allowPublicKeyRetrieval=true&useSSL=false

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  main:
    allow-bean-definition-overriding: 'true'
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}