spring:
  rabbitmq:
    password: '123456'
    port: '5672'
    host: localhost
    username: admin
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: kafka-log-topic
  application:
    name: kredinbizde-service
  main:
    allow-bean-definition-overriding: 'true'
rabbitmq:
  queue: patika.queue
  exchange: patika.exchange
  routingkey: patika.routingkey
server:
  port: '8080'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka