server:
  port: '5556'

management:
  endpoint:
    health:
      show-details: always
  health:
    kafka:
      enabled: true
    mysql:
      enabled: true
    defaults:
      enabled: false
spring:
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  application:
    name: akbank-service-main
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: example
    url: jdbc:mysql://${MYSQL_DB_HOST:localhost}:3306/test?allowPublicKeyRetrieval=true&useSSL=false
  kafka:
    producer:
      acks: -1
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    template:
      default-topic: kafka-log-topic
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}